# Generated by Django 5.2.17 on 2026-08-13 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'management_project',
                'ordering': ['project_name'],
                'indexes': [models.Index(fields=['active'], name='management__active_cb596e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('project_name__regex', '^\\s*.+\\s*$')), name='ck_management_project_name_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='ManagementTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'management_tag',
                'ordering': ['tag_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('tag_name__regex', '^\\s*.+\\s*$')), name='ck_management_tag_name_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='CashFlowEntryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_link', to='transactions.cashflowentry')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_links', to='management.managementproject')),
            ],
            options={
                'db_table': 'cash_flow_entry_project',
                'indexes': [models.Index(fields=['entry'], name='cash_flow_e_entry_i_9d12cd_idx'), models.Index(fields=['project'], name='cash_flow_e_project_ce7689_idx')],
                'constraints': [models.UniqueConstraint(fields=('entry',), name='uq_cash_flow_entry_project_entry')],
            },
        ),
        migrations.CreateModel(
            name='CashFlowEntryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='transactions.cashflowentry')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_links', to='management.managementtag')),
            ],
            options={
                'db_table': 'cash_flow_entry_tag',
                'indexes': [models.Index(fields=['entry'], name='cash_flow_e_entry_i_6649ec_idx'), models.Index(fields=['tag'], name='cash_flow_e_tag_id_ef71b8_idx')],
                'constraints': [models.UniqueConstraint(fields=('entry', 'tag'), name='uq_cash_flow_entry_tag_entry_tag')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='transactions.cashflowcategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounts.accountowner')),
            ],
            options={
                'db_table': 'monthly_budget',
                'ordering': ['owner', 'year', 'month'],
                'indexes': [models.Index(fields=['owner', 'year', 'month'], name='monthly_bud_owner_i_86cda3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='ck_monthly_budget_month_range'), models.CheckConstraint(condition=models.Q(('year__gte', 2000), ('year__lte', 2100)), name='ck_monthly_budget_year_range'), models.CheckConstraint(condition=models.Q(('planned_amount__gte', 0)), name='ck_monthly_budget_amount_non_negative'), models.UniqueConstraint(fields=('owner', 'category', 'year', 'month'), name='uq_monthly_budget_owner_category_period')],
            },
        ),
    ]
