# Generated by Django 5.2 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="managementtag",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="monthlybudget",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="managementtag",
            index=models.Index(fields=["active"], name="management__active_6f4382_idx"),
        ),
        migrations.AddIndex(
            model_name="monthlybudget",
            index=models.Index(fields=["active"], name="monthly_bud_active_b87bbb_idx"),
        ),
    ]
