# Generated by Django 5.2.17 on 2026-08-13 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=50, unique=True)),
                ('setting_value', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_setting',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=80, null=True)),
                ('action', models.CharField(max_length=80)),
                ('old_values_json', models.JSONField(blank=True, null=True)),
                ('new_values_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['entity_name', 'entity_id'], name='ix_audit_log_entity'), models.Index(fields=['created_at'], name='ix_audit_log_created_at'), models.Index(fields=['user'], name='ix_audit_log_user')],
                'constraints': [models.CheckConstraint(condition=models.Q(('entity_name', ''), _negated=True), name='ck_audit_log_entity_name_not_blank'), models.CheckConstraint(condition=models.Q(('action', ''), _negated=True), name='ck_audit_log_action_not_blank')],
            },
        ),
    ]
