# Generated by Django 5.2.17 on 2026-08-13 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountvisibility',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_visibility_preferences', to='banking.financialaccount'),
        ),
        migrations.AddField(
            model_name='useraccountvisibility',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_visibility_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userowneraccess',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountowner'),
        ),
        migrations.AddField(
            model_name='userowneraccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='accounts.apppermission'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['user_type'], name='app_user_user_ty_35760d_idx'),
        ),
        migrations.AddConstraint(
            model_name='appuser',
            constraint=models.CheckConstraint(condition=models.Q(('user_type__in', ('administrator', 'super user', 'user'))), name='ck_app_user_user_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='appuser',
            constraint=models.CheckConstraint(condition=models.Q(('ui_theme__in', ('light', 'dark', 'solarized_light', 'solarized_dark', 'dracula', 'nord', 'monokai', 'gray', 'soft_light', 'soft_dark', 'corporate_blue', 'emerald'))), name='ck_app_user_ui_theme_valid'),
        ),
        migrations.AddConstraint(
            model_name='appuser',
            constraint=models.CheckConstraint(condition=models.Q(('table_scroll_rows__gte', 5), ('table_scroll_rows__lte', 200)), name='ck_app_user_table_scroll_rows_range'),
        ),
        migrations.AddIndex(
            model_name='useraccountvisibility',
            index=models.Index(fields=['user'], name='user_accoun_user_id_c20846_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccountvisibility',
            index=models.Index(fields=['account'], name='user_accoun_account_326687_idx'),
        ),
        migrations.AddConstraint(
            model_name='useraccountvisibility',
            constraint=models.UniqueConstraint(fields=('user', 'account'), name='uq_user_account_visibility_user_account'),
        ),
        migrations.AddIndex(
            model_name='userowneraccess',
            index=models.Index(fields=['user', 'owner'], name='user_owner__user_id_23b631_idx'),
        ),
        migrations.AddConstraint(
            model_name='userowneraccess',
            constraint=models.UniqueConstraint(fields=('user', 'owner'), name='uq_user_owner_access_user_owner'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user'], name='user_permis_user_id_281a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['permission'], name='user_permis_permiss_0999ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='userpermission',
            constraint=models.UniqueConstraint(fields=('user', 'permission'), name='uq_user_permission_user_permission'),
        ),
    ]
