# Generated by Django 5.2.12 on 2026-08-31

from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remover_permissoes_orfas_de_agosto"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="accountowner",
            constraint=models.UniqueConstraint(Lower("name"), name="uq_account_owner_name_ci"),
        ),
    ]
