# Generated by Django 6.1.1 on 2026-09-24 14:56
#
# Remove Configurações > Contas em análises (`user_account_visibility`). A tela
# servia para simular o recorte que o filtro global de grupos de conta
# (`core/account_group_filter.py`) passou a fazer. As preferências gravadas
# (5 linhas em produção em 24/09/2026) são descartadas por decisão do dono do
# sistema, com backup do banco feito antes. Reverter recria a tabela vazia.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_transfer_destination_access'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='useraccountvisibility',
            name='user_accoun_user_id_c20846_idx',
        ),
        migrations.RemoveIndex(
            model_name='useraccountvisibility',
            name='user_accoun_account_326687_idx',
        ),
        migrations.RemoveConstraint(
            model_name='useraccountvisibility',
            name='uq_user_account_visibility_user_account',
        ),
        migrations.DeleteModel(
            name='UserAccountVisibility',
        ),
    ]
