# Generated by Django 5.2.17 on 2026-08-13 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('institution_type', models.CharField(choices=[('Banco', 'Banco'), ('Corretora', 'Corretora')], default='Banco', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'financial_institution',
                'ordering': ['institution_name'],
                'indexes': [models.Index(fields=['institution_type'], name='financial_i_institu_8bfbaa_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('institution_name__regex', '^\\s*.+\\s*$')), name='ck_financial_institution_name_not_blank'), models.CheckConstraint(condition=models.Q(('institution_type__in', ['Banco', 'Corretora'])), name='ck_financial_institution_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.accountowner')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='banking.financialinstitution')),
            ],
            options={
                'db_table': 'financial_account',
                'ordering': ['account_name'],
                'indexes': [models.Index(fields=['owner'], name='financial_a_owner_i_7633fc_idx'), models.Index(fields=['institution'], name='financial_a_institu_5cc945_idx'), models.Index(fields=['is_default'], name='financial_a_is_defa_1e20db_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('account_name__regex', '^\\s*.+\\s*$')), name='ck_financial_account_name_not_blank')],
            },
        ),
    ]
