# Generated by Django 5.2.12 on 2026-08-31

from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0002_financialinstitution_homologada"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="financialinstitution",
            constraint=models.UniqueConstraint(Lower("institution_name"), name="uq_financial_institution_name_ci"),
        ),
    ]
