# Generated by Django 6.1.1 on 2026-09-23 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_transfer_destination_access'),
        ('banking', '0004_conta_moeda_e_data_do_saldo_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='account_kind',
            field=models.CharField(choices=[('conta', 'Conta'), ('cartao_credito', 'Cartão de crédito')], default='conta', max_length=20),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='card_closing_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='card_due_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='card_payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_paid', to='banking.financialaccount'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.CheckConstraint(condition=models.Q(('account_kind__in', ('conta', 'cartao_credito'))), name='ck_financial_account_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account_kind', 'cartao_credito'), ('card_closing_day__gte', 1), ('card_closing_day__isnull', False), ('card_closing_day__lte', 31), ('card_due_day__gte', 1), ('card_due_day__isnull', False), ('card_due_day__lte', 31)), models.Q(('account_kind', 'conta'), ('card_closing_day__isnull', True), ('card_due_day__isnull', True), ('card_payment_account__isnull', True)), _connector='OR'), name='ck_financial_account_card_fields'),
        ),
    ]
