# Generated by Django 6.1.1 on 2026-09-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_transfer_destination_access'),
        ('banking', '0005_conta_tipo_cartao_de_credito'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='financialaccount',
            name='ck_financial_account_card_fields',
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='card_estimated_spend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account_kind', 'cartao_credito'), ('card_closing_day__gte', 1), ('card_closing_day__isnull', False), ('card_closing_day__lte', 31), ('card_due_day__gte', 1), ('card_due_day__isnull', False), ('card_due_day__lte', 31), models.Q(('card_estimated_spend__isnull', True), ('card_estimated_spend__gte', 0), _connector='OR')), models.Q(('account_kind', 'conta'), ('card_closing_day__isnull', True), ('card_due_day__isnull', True), ('card_estimated_spend__isnull', True), ('card_payment_account__isnull', True)), _connector='OR'), name='ck_financial_account_card_fields'),
        ),
    ]
