# Generated by Django 6.1.1 on 2026-09-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_transfer_destination_access'),
        ('banking', '0006_cartao_gasto_estimado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='financialaccount',
            name='ck_financial_account_kind_valid',
        ),
        migrations.RemoveConstraint(
            model_name='financialaccount',
            name='ck_financial_account_card_fields',
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='account_kind',
            field=models.CharField(choices=[('conta', 'Conta'), ('cartao_credito', 'Cartão de crédito'), ('aplicacao', 'Aplicação')], default='conta', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.CheckConstraint(condition=models.Q(('account_kind__in', ('conta', 'cartao_credito', 'aplicacao'))), name='ck_financial_account_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account_kind', 'cartao_credito'), ('card_closing_day__gte', 1), ('card_closing_day__isnull', False), ('card_closing_day__lte', 31), ('card_due_day__gte', 1), ('card_due_day__isnull', False), ('card_due_day__lte', 31), models.Q(('card_estimated_spend__isnull', True), ('card_estimated_spend__gte', 0), _connector='OR')), models.Q(('account_kind__in', ('conta', 'aplicacao')), ('card_closing_day__isnull', True), ('card_due_day__isnull', True), ('card_estimated_spend__isnull', True), ('card_payment_account__isnull', True)), _connector='OR'), name='ck_financial_account_card_fields'),
        ),
    ]
