# Generated by Django 6.1.1 on 2026-10-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_mercadopago_homologada'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='statement_identifier',
            field=models.CharField(blank=True, default='', help_text='Número da conta como aparece no extrato do banco (com ou sem pontuação). Usado para reconhecer automaticamente a conta ao importar vários extratos de uma vez; a comparação ignora tudo que não for dígito.', max_length=40),
        ),
    ]
