# Generated by Django 6.1.1 on 2026-10-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remover_contas_em_analises'),
        ('banking', '0009_financialaccount_statement_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='purpose',
            field=models.CharField(choices=[('pessoal', 'Pessoal'), ('administrada', 'Administrada (de terceiros)')], default='pessoal', help_text='Pessoal ou administrada (dinheiro de terceiros que o titular só gere).', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ('pessoal', 'administrada'))), name='ck_financial_account_purpose_valid'),
        ),
    ]
