# Generated by Django 6.1.1 on 2026-10-06 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0012_itau_homologada'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='movement_account',
            field=models.ForeignKey(blank=True, help_text='Só para aplicação: a conta corrente por onde o dinheiro entra e sai.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_investments', to='banking.financialaccount'),
        ),
    ]
