# Generated by Django 5.2.17 on 2026-08-13 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_key', models.CharField(max_length=80, unique=True)),
                ('legacy_operation_id', models.CharField(blank=True, max_length=36, null=True)),
                ('operation_type', models.CharField(choices=[('single', 'Única'), ('installment', 'Parcelado'), ('recurring', 'Recorrente'), ('internal_transfer', 'Transferência Interna')], default='single', max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('a_vencer', 'A vencer'), ('vencidos', 'Vencidos'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='a_vencer', max_length=20)),
                ('installment_total', models.IntegerField(default=1)),
                ('first_due_date', models.DateField(blank=True, null=True)),
                ('last_due_date', models.DateField(blank=True, null=True)),
                ('entry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bank_operation',
                'indexes': [models.Index(fields=['legacy_operation_id'], name='bank_operat_legacy__079fe1_idx'), models.Index(fields=['operation_type', 'status'], name='bank_operat_operati_aeaa75_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('operation_key__regex', '^\\s*.+\\s*$')), name='ck_bank_operation_key_not_blank'), models.CheckConstraint(condition=models.Q(('operation_type__in', ['single', 'installment', 'recurring', 'internal_transfer'])), name='ck_bank_operation_type_valid'), models.CheckConstraint(condition=models.Q(('status__in', ('a_vencer', 'vencidos', 'realizado', 'cancelado'))), name='ck_bank_operation_status_valid'), models.CheckConstraint(condition=models.Q(('installment_total__gte', 1)), name='ck_bank_operation_installment_total_positive'), models.CheckConstraint(condition=models.Q(('entry_count__gte', 0)), name='ck_bank_operation_entry_count_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='CashFlowCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cash_flow_category',
                'ordering': ['category_name'],
                'indexes': [models.Index(fields=['is_internal'], name='cash_flow_c_is_inte_ca4eaa_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('category_name__regex', '^\\s*.+\\s*$')), name='ck_cash_flow_category_name_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='AccountMonthClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closed_at', models.DateTimeField()),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_closes', to='banking.financialaccount')),
                ('closed_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_months', to=settings.AUTH_USER_MODEL)),
                ('reopened_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_months', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_month_close',
                'indexes': [models.Index(fields=['account', 'year', 'month'], name='account_mon_account_d74e4e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='ck_account_month_close_month_range'), models.CheckConstraint(condition=models.Q(('year__gte', 2000), ('year__lte', 2100)), name='ck_account_month_close_year_range'), models.UniqueConstraint(fields=('account', 'year', 'month'), name='uq_account_month_close_account_period')],
            },
        ),
        migrations.CreateModel(
            name='CashFlowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('entry_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installments', models.IntegerField(default=1)),
                ('current_installment', models.IntegerField(default=1)),
                ('due_date', models.DateField()),
                ('realized_date', models.DateField(blank=True, null=True)),
                ('realized_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('a_vencer', 'A vencer'), ('vencidos', 'Vencidos'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='a_vencer', max_length=20)),
                ('operation_type', models.CharField(db_index=True, default='single', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='banking.financialaccount')),
                ('bank_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='transactions.bankoperation')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.cashflowcategory')),
                ('source_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_entries', to='transactions.cashflowentry')),
            ],
            options={
                'db_table': 'cash_flow_entry',
                'indexes': [models.Index(fields=['account', 'due_date'], name='cash_flow_e_account_a69989_idx'), models.Index(fields=['account', 'realized_date'], name='cash_flow_e_account_d0e6a6_idx'), models.Index(fields=['category', 'due_date'], name='cash_flow_e_categor_4bd7a1_idx'), models.Index(fields=['status', 'due_date'], name='cash_flow_e_status_b1ed23_idx'), models.Index(fields=['entry_type', 'due_date'], name='cash_flow_e_entry_t_35524d_idx'), models.Index(fields=['operation_type'], name='cash_flow_e_operati_60d3fd_idx'), models.Index(fields=['bank_operation'], name='cash_flow_e_bank_op_65cc45_idx'), models.Index(fields=['source_entry'], name='cash_flow_e_source__2bb4eb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('entry_type__in', ('receita', 'despesa'))), name='ck_cash_flow_entry_type_valid'), models.CheckConstraint(condition=models.Q(('entry_amount__gt', 0)), name='ck_cash_flow_entry_amount_positive'), models.CheckConstraint(condition=models.Q(('realized_amount__isnull', True), ('realized_amount__gt', 0), _connector='OR'), name='ck_cash_flow_entry_realized_amount_positive'), models.CheckConstraint(condition=models.Q(('status__in', ('a_vencer', 'vencidos', 'realizado', 'cancelado'))), name='ck_cash_flow_entry_status_valid'), models.CheckConstraint(condition=models.Q(('operation_type__in', ['single', 'installment', 'recurring', 'internal_transfer'])), name='ck_cash_flow_entry_operation_type_valid'), models.CheckConstraint(condition=models.Q(('installments__gte', 1)), name='ck_cash_flow_entry_installments_positive'), models.CheckConstraint(condition=models.Q(('current_installment__gte', 1)), name='ck_cash_flow_entry_current_installment_positive'), models.CheckConstraint(condition=models.Q(('current_installment__lte', models.F('installments'))), name='ck_cash_flow_entry_current_lte_total'), models.CheckConstraint(condition=models.Q(('source_entry__isnull', True), models.Q(('source_entry', models.F('id')), _negated=True), _connector='OR'), name='ck_cash_flow_entry_source_not_self')],
            },
        ),
    ]
