# Generated by Django 6.1.1 on 2026-10-02 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_integridade_da_transferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowCategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('position', models.PositiveSmallIntegerField(default=100)),
                ('in_charts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cash_flow_category_group',
                'ordering': ['position', 'group_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('group_name__regex', '^\\s*.+\\s*$')), name='ck_cash_flow_category_group_name_not_blank')],
            },
        ),
        migrations.AddField(
            model_name='cashflowcategory',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='transactions.cashflowcategorygroup'),
        ),
    ]
