# Generated by Django 6.1.1 on 2026-10-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_grupos_de_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioDeLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'cash_flow_entry_submission',
            },
        ),
    ]
