# Generated by Django 5.2.17 on 2026-08-13 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('row_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('importado', 'Importado'), ('processado', 'Processado'), ('erro', 'Erro')], default='importado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_imports', to='banking.financialaccount')),
            ],
            options={
                'db_table': 'bank_statement_import',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('conciliado', 'Conciliado'), ('ignorado', 'Ignorado')], default='novo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_lines', to='banking.financialaccount')),
                ('import_batch', models.ForeignKey(db_column='import_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bank_statements.bankstatementimport')),
                ('matched_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statement_matches', to='transactions.cashflowentry')),
            ],
            options={
                'db_table': 'bank_statement_line',
                'ordering': ['-statement_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EntryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=120, null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='transactions.cashflowentry')),
            ],
            options={
                'db_table': 'entry_attachment',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='bankstatementimport',
            index=models.Index(fields=['account'], name='bank_statem_account_9e538c_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementimport',
            index=models.Index(fields=['created_at'], name='bank_statem_created_d3578a_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementimport',
            constraint=models.CheckConstraint(condition=models.Q(('source_filename__regex', '^\\s*.+\\s*$')), name='ck_bank_statement_import_filename_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementimport',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('importado', 'processado', 'erro'))), name='ck_bank_statement_import_status_valid'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['account', 'statement_date'], name='bank_statem_account_a5fa76_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['import_batch'], name='bank_statem_import__79616d_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['matched_entry'], name='bank_statem_matched_eaa62f_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['status'], name='bank_statem_status_c3a475_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='ck_bank_statement_line_amount_non_zero'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('novo', 'conciliado', 'ignorado'))), name='ck_bank_statement_line_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.UniqueConstraint(fields=('account', 'line_hash'), name='uq_bank_statement_line_account_hash'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.UniqueConstraint(condition=models.Q(('matched_entry__isnull', False), ('status', 'conciliado')), fields=('matched_entry',), name='uq_bank_statement_line_active_matched_entry'),
        ),
        migrations.AddIndex(
            model_name='entryattachment',
            index=models.Index(fields=['entry'], name='entry_attac_entry_i_bb47db_idx'),
        ),
        migrations.AddConstraint(
            model_name='entryattachment',
            constraint=models.CheckConstraint(condition=models.Q(('original_filename__regex', '^\\s*.+\\s*$')), name='ck_entry_attachment_filename_not_blank'),
        ),
    ]
