# Generated by Django 6.1.1 on 2026-09-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statements', '0001_initial'),
        ('banking', '0005_conta_tipo_cartao_de_credito'),
        ('transactions', '0006_encerramento_da_recorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementline',
            name='bank_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='card_holder',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='installment_current',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='installment_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('installment_current__isnull', True), ('installment_total__isnull', True)), models.Q(('installment_current__gte', 1), ('installment_current__isnull', False), ('installment_current__lte', models.F('installment_total')), ('installment_total__isnull', False)), _connector='OR'), name='ck_bank_statement_line_installment_valid'),
        ),
    ]
