# Generated by Django 6.1.1 on 2026-10-01 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statements', '0002_fatura_de_cartao'),
        ('banking', '0009_financialaccount_statement_identifier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingStatementUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=120, null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('detected_label', models.CharField(blank=True, max_length=255)),
                ('detection_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detected_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_statement_uploads', to='banking.financialaccount')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_statement_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pending_statement_upload',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['uploaded_by'], name='pending_sta_uploade_548878_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('original_filename__regex', '^\\s*.+\\s*$')), name='ck_pending_statement_upload_filename_not_blank')],
            },
        ),
    ]
