# Generated by Django 6.1.1 on 2026-10-02 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statements', '0003_pendingstatementupload'),
        ('banking', '0009_financialaccount_statement_identifier'),
        ('transactions', '0008_integridade_da_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementimport',
            name='statement_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='statement_balance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StatementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pattern', models.CharField(max_length=120)),
                ('sign', models.CharField(choices=[('qualquer', 'Entrada ou saída'), ('credito', 'Só entrada'), ('debito', 'Só saída')], default='qualquer', max_length=10)),
                ('action', models.CharField(choices=[('categoria', 'Categorizar'), ('transferencia', 'Transferência para conta do mesmo titular'), ('ignorar', 'Ignorar a linha')], max_length=20)),
                ('destination_account_name', models.CharField(blank=True, default='', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statement_rules', to='transactions.cashflowcategory')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement_rules', to='banking.financialinstitution')),
            ],
            options={
                'db_table': 'statement_rule',
                'ordering': ['name', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('pattern__regex', '^\\s*.{3,}\\s*$')), name='ck_statement_rule_pattern_min_length'), models.CheckConstraint(condition=models.Q(('action__in', ('categoria', 'transferencia', 'ignorar'))), name='ck_statement_rule_action_valid'), models.CheckConstraint(condition=models.Q(('sign__in', ('qualquer', 'credito', 'debito'))), name='ck_statement_rule_sign_valid'), models.CheckConstraint(condition=models.Q(models.Q(('action', 'categoria'), ('category__isnull', False)), models.Q(('action', 'transferencia'), ('destination_account_name__regex', '^\\s*.+\\s*$')), ('action', 'ignorar'), _connector='OR'), name='ck_statement_rule_action_fields')],
            },
        ),
    ]
