# Generated by Django 6.1.1 on 2026-10-02 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statements', '0004_regras_e_saldo_do_extrato'),
        ('banking', '0011_xp_investimentos_homologada'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementrule',
            name='destination_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement_rules_as_destination', to='banking.financialinstitution'),
        ),
    ]
