# Generated by Django 6.1.1 on 2026-10-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statements', '0005_regra_com_instituicao_de_destino'),
        ('banking', '0013_conta_de_movimento_da_aplicacao'),
        ('transactions', '0009_grupos_de_categoria'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='statementrule',
            name='ck_statement_rule_action_valid',
        ),
        migrations.RemoveConstraint(
            model_name='statementrule',
            name='ck_statement_rule_action_fields',
        ),
        migrations.AlterField(
            model_name='statementrule',
            name='action',
            field=models.CharField(choices=[('categoria', 'Categorizar'), ('transferencia', 'Transferência para conta do mesmo titular'), ('ignorar', 'Ignorar a linha'), ('aplicacao', 'Transferência para a aplicação vinculada à conta')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='statementrule',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ('categoria', 'transferencia', 'ignorar', 'aplicacao'))), name='ck_statement_rule_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='statementrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'categoria'), ('category__isnull', False)), models.Q(('action', 'transferencia'), ('destination_account_name__regex', '^\\s*.+\\s*$')), ('action', 'ignorar'), ('action', 'aplicacao'), _connector='OR'), name='ck_statement_rule_action_fields'),
        ),
    ]
