# Generated by Django 6.1.1 on 2026-10-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statements', '0006_regra_para_aplicacao_vinculada'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementimport',
            name='statement_period_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
